const SECOND = 1000;
const MINUTE = 60 * 1000;

export const timeouts = {
	HALF_SEC: SECOND / 2,
	ONE_SEC: SECOND,
	TWO_SEC: SECOND * 2,
	FOUR_SEC: SECOND * 4,
	TEN_SEC: SECOND * 10,
	HALF_MIN: MINUTE / 2,
	ONE_MIN: MINUTE,
};
